import { configureStore, createSlice } from '@reduxjs/toolkit';

// Create a slice for user authentication
const userSlice = createSlice({
    name: 'user',
    initialState: { isLoggedIn: false },
    reducers: {
        login(state) {
            state.isLoggedIn = true;
        },
        logout(state) {
            localStorage.removeItem("userId");
            state.isLoggedIn = false;
        }
    }
});

// Export the user actions generated by the slice
export const userActions = userSlice.actions;

// Create a slice for admin authentication
const adminSlice = createSlice({
    name: 'auth',
    initialState: { isLoggedIn: false },
    reducers: {
        login(state) {
            state.isLoggedIn = true;
        },
        logout(state) {
            localStorage.removeItem("adminId");
            localStorage.removeItem("token");
            state.isLoggedIn = false;
        }
    }
});

// Export the admin actions generated by the slice
export const adminActions = adminSlice.actions;

// Configure and export the Redux store for user and admin
export const store = configureStore({
    reducer: {
        user: userSlice.reducer,
        admin: adminSlice.reducer
    }
});
